// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameApp = "app"

// App mapped from table <app>
type App struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	AppName    string    `gorm:"column:app_name" json:"app_name"`
	CreateTime time.Time `gorm:"column:create_time" json:"create_time"`
	Desc       string    `gorm:"column:desc" json:"desc"`
	Remark     string    `gorm:"column:remark" json:"remark"`
}

// TableName App's table name
func (*App) TableName() string {
	return TableNameApp
}
