// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAppPackage = "app_package"

// AppPackage mapped from table <app_package>
type AppPackage struct {
	ID             int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	PackageName    string    `gorm:"column:package_name" json:"package_name"`
	PackageLabel   string    `gorm:"column:package_label" json:"package_label"`
	PackageVersion string    `gorm:"column:package_version" json:"package_version"`
	Status         int32     `gorm:"column:status" json:"status"`
	Owner          string    `gorm:"column:owner" json:"owner"`
	CreateTime     time.Time `gorm:"column:create_time" json:"create_time"`
	UpdateTime     time.Time `gorm:"column:update_time" json:"update_time"`
}

// TableName AppPackage's table name
func (*AppPackage) TableName() string {
	return TableNameAppPackage
}
