// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAppInstance = "app_instance"

// AppInstance mapped from table <app_instance>
type AppInstance struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	AppName    string    `gorm:"column:app_name" json:"app_name"`
	CreateTime time.Time `gorm:"column:create_time" json:"create_time"`
	Desc       string    `gorm:"column:desc" json:"desc"`
	Remark     string    `gorm:"column:remark" json:"remark"`
	CreateUser User      `gorm:"foreignKey:create_user_id" json:"create_user"`
}

// TableName AppInstance's table name
func (*AppInstance) TableName() string {
	return TableNameAppInstance
}
