// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRole = "role"

// Role mapped from table <role>
type Role struct {
	ID       int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	RoleCode string `gorm:"column:role_code" json:"role_code"`
	RoleName string `gorm:"column:role_name" json:"role_name"`
	Status   int32  `gorm:"column:status" json:"status"`
}

// TableName Role's table name
func (*Role) TableName() string {
	return TableNameRole
}
