// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/plugin/soft_delete"
)

const TableNameSysDept = "sys_dept"

// SysDept mapped from table <sys_dept>
type SysDept struct {
	ID          int64                 `gorm:"column:id;primaryKey;autoIncrement:true;comment:id" json:"id"` // id
	ParentID    *int64                `gorm:"column:parent_id" json:"parent_id"`
	DeptName    *string               `gorm:"column:dept_name" json:"dept_name"`
	CreateTime  *time.Time            `gorm:"column:create_time;autoCreateTime:true" json:"create_time"`
	UpdateTime  *time.Time            `gorm:"column:update_time;autoUpdateTime:true" json:"update_time"`
	DeleteTime  *time.Time            `gorm:"column:delete_time" json:"delete_time"`
	DelFlag     soft_delete.DeletedAt `gorm:"column:del_flag;softDelete:flag" json:"del_flag"`
	Remark      *string               `gorm:"column:remark" json:"remark"`
	SysUserList []*SysUser            `gorm:"References:ID;foreignKey:ID" json:"sys_user_list"`
}

// TableName SysDept's table name
func (*SysDept) TableName() string {
	return TableNameSysDept
}
